### ISSUE TITLE
Set up configuration options as an object.

### ISSUE THREAD

**Issue by JackWFinlay** [JackWFinlay/jsonize#14]
I want to set up configuration options as an object to be passed to the method so that parameters on the method aren't constantly changing. A good example is Newtonsoft.Json's JsonSerializer class.

**Comment by feeeper** [comment]
Can you please tell more about the issue? Do you talking about [`ParseHtmlAsJson`](https://github.com/JackWFinlay/jsonize/blob/master/src/jsonize/Jsonize.cs#L53) method? What parameters you want to pass as an object?

**Comment by JackWFinlay** [comment]
Yeah, the ParseHtmlAsJson method would then pass it on to GetChildren. Currently is like to see parameters for showEmptyTextNode and also for showing null values. If you can think of any more parameters you'd like to see that will tweak the output, feel free to suggest them.

**Comment by JackWFinlay** [comment]
I have fixed this issue. See new code for details on how I'd like future config options set up.
