### ISSUE TITLE
Produce tests to increase coverage.

### ISSUE THREAD

**Issue by JackWFinlay** [JackWFinlay/jsonize#20]
Currently the tests are very basic and don't accurately cover the methods being tested (they just run the methods and the output is inspected manually). Proper test cases need to be set up. Currently we are using nUnitlite.

**Comment by feeeper** [comment]
Is it necessarily to use NUnitLite? It will be easier to use xUnit instead of NUnitLite.

**Comment by CJWhaley17** [comment]
This is something I would like to try to assist with, but I have only used nUnit and test3runner. Would that be okay?

**Comment by JackWFinlay** [comment]
@CoreyWhaley, absolutely. I don't really mind, as long as the coverage is good, accurate and expandable.

**Comment by CJWhaley17** [comment]
@JackWFinlay Sounds good. I will dive into that this weekend and next week as I have it off. Cheers.
