### ISSUE TITLE
Refactor to only call the Http endpoint once for the whole set of tests.

### ISSUE THREAD

**Issue by JackWFinlay** [JackWFinlay/jsonize#22]
Currently the test package is calling the http endpoint once per test and this slow and wasteful. The tests need to be refactored to only call it once at the start of the test program.

**Comment by darkwizz** [comment]
hello, which type of project does have Jsonize.Test? My VS (2015 CE update 3) can't load it

**Comment by JackWFinlay** [comment]
@darkwiz, It's just a  .NET framework 4.6 console app. This issue has been been handled by @rmnblm. Looks like I need to put in some guidelines for contributing - I need people to comment when they are picking up an issue so we don't get two people working on the same thing.

Anyway, I'm just about to accept that PR that fixes this. Feel free to fix any other issues you like!

**Comment by rmnblm** [comment]
Thanks Jack. 

Yes, contributing guidelines would be great. You may face this problem that two people are working on the same issue during the Hacktoberfest more often 😉 

I will later in the evening!

**Comment by JackWFinlay** [comment]
Cool, I'll write some guidelines up in the morning - it's nearly 4am here (NZDT).

**Comment by rmnblm** [comment]
If you repo is going to grow you should also consider creating a development branch.
It's nearly 5pm here in 🇨🇭  :)

**Comment by JackWFinlay** [comment]
I'll do that in the morning too. Thanks. This is my first successful collaborative github project, so I don't exactly know how to manage everything just yet.
