### ISSUE TITLE
Unable to resolve 'Jsonize' for '.NETCoreApp,Version=v1.0'

### ISSUE THREAD

**Issue by rmnblm** [JackWFinlay/jsonize#24]
I'm getting above error when running `dotnet restore` and can't getting it to work (whether on Windows or on macOS). Any ideas? 

**dotnet --info** on Windows
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  (hidden)

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**dotnet --info** on macOS
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  (hidden)

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

<img width="252" alt="screen shot 2016-10-08 at 14 03 12" src="https://cloud.githubusercontent.com/assets/5942764/19212991/01bbb8f0-8d60-11e6-8802-3f476e05d13a.png">

**Comment by rmnblm** [comment]
Fixed this error by changing the package name in the `project.json` under Jsonize.Test to 

```
"JackWFinlay.Jsonize": "*",
```

**Comment by JackWFinlay** [comment]
Thanks for your issue, I was having the same ( but it still ran properly for me). I noticed that in your pull request you have something different. Which way works properly?

**Comment by rmnblm** [comment]
Hi Jack

Well to just **use** Jsonize I can reference the NuGet package by it's name, which is `JackWFinlay.Jsonize` but for local development I need to reference the local project to be able to use features which aren't published yet (like for example the `TextTrimHandling` property).

```
"Jsonize": {
    "target":  "project"
}
```

I wasn't able to restore the `Jsonize` package without this change (my development environment is macOS).

**Comment by JackWFinlay** [comment]
Right, thanks. I think it's best to leave it at what you have now so that we can test the latest functions. Tests will only really be run in a dev environment anyway. We can build another project if we want to test the released version. Looks like you might have solved an issue I've been having for a while, thanks.

**Comment by rmnblm** [comment]
Glad I could help you (took me more than an hour to solve this problem before I could even work on your issue).
