### ISSUE TITLE
Incorrect <form> tag processing

### ISSUE THREAD

**Issue by feeeper** [JackWFinlay/jsonize#26]
I start working on tests and found some problem (or may be I misunderstanding <form> tag processing).

My test:

``` C#
Jsonize jsonize = new Jsonize("<html><head></head><body><form></form></body></html>");
var result = jsonize.ParseHtmlAsJsonString(jsonizeConfiguration);
```

Result JSON string: 

``` JSON
{
  "node": "Document",
  "child": [
    {
      "node": "Element",
      "tag": "html",
      "child": [
        {
          "tag": "head"
        },
        {
          "node": "Element",
          "tag": "body",
          "child": [
            {
              "tag": "form"
            },
            {
              "node": "Text",
              "text": "</form>"
            }
          ]
        }
      ]
    }
  ]
}
```

Is it true that node "Text" with text "&lt;/form&gt;" is not correct? And it should look so:

``` JSON
{
  "node": "Document",
  "child": [
    {
      "tag": "html",
      "child": [
        {
          "tag": "head"
        },
        {
          "tag": "body",
          "child": [
            {
              "tag": "form"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by JackWFinlay** [comment]
Nice find. You are correct, the second case should be the proper result. I'll have to address that when I have some time. 

Just out of curiosity, what happens when you put some elements inside the form?

**Comment by feeeper** [comment]
I inserted input inside the form and got the result:

``` JSON
{
  "node": "Document",
  "child": [
    {
      "node": "Element",
      "tag": "html",
      "child": [
        {
          "tag": "head"
        },
        {
          "node": "Element",
          "tag": "body",
          "child": [
            {
              "tag": "form"
            },
            {
              "tag": "input"
            },
            {
              "node": "Text",
              "text": "</form>"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by JackWFinlay** [comment]
Interesting. I'll definitely have to fix that, or you can give it a go If you'd like. Thanks for spotting that. I think it may be an issue with HtmlAgilityPack. We can probably intercept it if it is form node and do some manual of our own processing.

**Comment by feeeper** [comment]
First of all I'll add the test for the case (today or tomorrow) :) And then I'll try to figure out what the problem.

**Comment by feeeper** [comment]
I send the PR for the issue.

PS: Can you add `Hacktoberfest` label for the issue, please?
