### ISSUE TITLE
Port to .NET 4.6

### ISSUE THREAD

**Issue by JackWFinlay** [JackWFinlay/jsonize#3]
Need to create another version to work with older versions of .NET. Can probably go further back than 4.6.

**Comment by bmeverett** [comment]
Since .NetCore is the basic level you can target almost any framework on top of that. I updated the project.json file to also target .net 4.6. Is this what you are looking for? 
https://github.com/bmeverett/jsonize/blob/netTarget46/src/jsonize/project.json#L30

**Comment by JackWFinlay** [comment]
Wow, it's really that simple? I'll have a go with it tonight and possibly pull that in. Thanks!

**Comment by JackWFinlay** [comment]
I went ahead and pulled your request. I had to update the dependencies, but it all works now. Thanks, @bmeverett !

**Comment by bmeverett** [comment]
No problem! Glad I could help!
