### ISSUE TITLE
Port tests from nUnitLite to xUnit

### ISSUE THREAD

**Issue by JackWFinlay** [JackWFinlay/jsonize#32]
Switched to xUnit in version 2.0.0 (new [jsonize-2.0.0](https://github.com/JackWFinlay/jsonize/tree/jsonize-2.0.0) branch) to reduce dependencies and make use of visual studio (& vscode) debugging and test runner features. Porting of tests is required. I know the tests are primitive, but some of them are useful. Discard any that require manual inspection (primarily the ones that download a string from a url). 

All new tests should have a defined input and assertions that the resulting output matches a given predefined expected output.

**Comment by Hekku2** [comment]
It seemed to me that there is only one test (`TestFormNodeShouldBeNode`) that doesn't download stuff from URL. Is this correct and you are just hoping to port that one test?
